version: '3.8'
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3001"
    volumes:
      - ./src/geodb:/usr/src/app/geodb
    depends_on:
      - geoipupdate
    environment:
      - NODE_ENV=development

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "3000:3000"
    volumes:
      - ./geodb:/usr/src/app/geodb
    depends_on:
      - geoipupdate
    environment:
      - NODE_ENV=production

  geoipupdate:
    image: maxmindinc/geoipupdate
    volumes:
      - ./src/geodb:/usr/share/GeoIP
    environment:
    - GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN,GeoLite2-City
    - GEOIPUPDATE_FREQUENCY=48
